esedjo_core:
    resource: "@EsedjoCoreBundle/Resources/config/routing.yml"
    prefix:   /

# app/config/routing.yml

esedjo_platform:
    resource: "@EsedjoPlatformBundle/Resources/config/routing.yml"
    prefix:   /platform