# src/Esedjo/PlatformBundle/Resources/config/routing.yml

esedjo_platform_homepage:
    path:     /hello/{name}
    defaults: { _controller: EsedjoPlatformBundle:Default:index }

hello_the_world:
    path:     /hello-world
    defaults: { _controller: EsedjoPlatformBundle:Advert:index }

index:
    path:     /index
    defaults: { _controller: EsedjoPlatformBundle:Advert:index }
